// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(EfContext))]
    partial class EfContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Departments.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Разработчики"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Юристы"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Начальники"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Реальные работники"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Эйчарочки"
                        });
                });

            modelBuilder.Entity("Domain.Employees.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "Саша Девопсов",
                            Salary = 100500.0
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Name = "Миша Тестин",
                            Salary = 12345.999089999999
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Name = "Артур Джунов",
                            Salary = 40000.0
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Name = "Семен Мидлин",
                            Salary = 100000.0
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            Name = "Денис Апачин",
                            Salary = 120000.0
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            Name = "Максим Сишарпин",
                            Salary = 150000.0
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 2,
                            Name = "Роман Таймсньюмов",
                            Salary = 100500.0
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 2,
                            Name = "Зина Адвокатова",
                            Salary = 140000.0
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 2,
                            Name = "Настя Судова",
                            Salary = 132000.0
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 2,
                            Name = "Олег Тожеадвокатов",
                            Salary = 120000.0
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 2,
                            Name = "Ярослав Посадилин",
                            Salary = 90000.0
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 2,
                            Name = "Ваня Студентов",
                            Salary = 40000.0
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 3,
                            Name = "Дима Главный",
                            Salary = 300500.0
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 3,
                            Name = "Никита Замглавов",
                            Salary = 200500.0
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 3,
                            Name = "Саша Секретарева",
                            Salary = 100500.0
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 3,
                            Name = "Олег Итуттоженачальников",
                            Salary = 120000.0
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 3,
                            Name = "Михаил Победоносный",
                            Salary = 90000.0
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 3,
                            Name = "Никита Стажёров",
                            Salary = 40000.0
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 4,
                            Name = "Вася Пупкин",
                            Salary = 50000.0
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 4,
                            Name = "Братвася Пупкин",
                            Salary = 45000.0
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 4,
                            Name = "Василина Пупкина",
                            Salary = 49999.0
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 4,
                            Name = "Иван Иванов",
                            Salary = 59000.0
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 4,
                            Name = "Виктор Рабочев",
                            Salary = 54000.0
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 4,
                            Name = "Георгий Нерабочев",
                            Salary = 30000.0
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 5,
                            Name = "Екатерина Вацапова",
                            Salary = 90000.0
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 5,
                            Name = "Алина Вайберова",
                            Salary = 86000.0
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 5,
                            Name = "Марина Хедхантеровна",
                            Salary = 110000.0
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 5,
                            Name = "Татьяна Телеграмина",
                            Salary = 106000.0
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 5,
                            Name = "Арина Топмесяцевна",
                            Salary = 130000.0
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 5,
                            Name = "Лера Последняя",
                            Salary = 99999.0
                        });
                });

            modelBuilder.Entity("Domain.Employees.Employee", b =>
                {
                    b.HasOne("Domain.Departments.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
